
package Frames;
import Clases.Categoria;
import Clases.Evento;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author User001
 */
public class CategoriaProductos extends javax.swing.JFrame {

    public InicioMicro padre;
    public String EventoSeleccionado;
    public String nickNameMicro;
    DefaultListModel modele = new DefaultListModel();
    List<Evento> categoria = new ArrayList<>();
    public CategoriaProductos(InicioMicro padre, String EventoSeleccionado, String nickNameMicro) {
        initComponents();
        this.padre= padre;
     this.EventoSeleccionado= EventoSeleccionado;
     this.nickNameMicro=nickNameMicro;
     lblRazonSocial.setText(nickNameMicro); 
    }

    private CategoriaProductos() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategorias = new javax.swing.JList<>();
        bttAgregarCatPro = new javax.swing.JButton();
        bttVolverCPC = new javax.swing.JButton();
        lblRazonSocial = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttSeleccionarCatPro = new javax.swing.JButton();
        bttEliminarCatPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Productos");

        lstCategorias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstCategorias);

        bttAgregarCatPro.setText("Agregar Categoria");
        bttAgregarCatPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregarCatProActionPerformed(evt);
            }
        });

        bttVolverCPC.setText("Volver");
        bttVolverCPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVolverCPCActionPerformed(evt);
            }
        });

        lblRazonSocial.setText("jLabel2");

        jLabel2.setText("Seleccionar categoria");

        bttSeleccionarCatPro.setText("Seleccionar Categoria");
        bttSeleccionarCatPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSeleccionarCatProActionPerformed(evt);
            }
        });

        bttEliminarCatPro.setText("Eliminar Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(lblRazonSocial)
                        .addGap(104, 104, 104))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttVolverCPC)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bttAgregarCatPro)
                                    .addComponent(bttSeleccionarCatPro)
                                    .addComponent(bttEliminarCatPro)))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazonSocial)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttAgregarCatPro)
                                .addGap(18, 18, 18)
                                .addComponent(bttSeleccionarCatPro)
                                .addGap(18, 18, 18)
                                .addComponent(bttEliminarCatPro)))))
                .addGap(26, 26, 26)
                .addComponent(bttVolverCPC)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttVolverCPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVolverCPCActionPerformed
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttVolverCPCActionPerformed

    private void bttAgregarCatProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregarCatProActionPerformed
        AgregarCategoriaProductos ventanacurso = new AgregarCategoriaProductos(this);
        ventanacurso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttAgregarCatProActionPerformed

    private void bttSeleccionarCatProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSeleccionarCatProActionPerformed
         String categoriaSeleccionada = lstCategorias.getSelectedValue();

    if (categoriaSeleccionada != null) {
        ListaProductos ventanacurso = new ListaProductos(this,categoriaSeleccionada,nickNameMicro);
        ventanacurso.setVisible(true);
        this.setVisible(false);
    }
    }//GEN-LAST:event_bttSeleccionarCatProActionPerformed

    public void agregarCategoriaProALista(String NombreCategoria) {
     Categoria nuevaCategoria = new Categoria(NombreCategoria);
     categoria.add(nuevaCategoria);
     modele.addElement(NombreCategoria +"|"+ EventoSeleccionado);
     lstCategorias.setModel(modele);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CategoriaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CategoriaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CategoriaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CategoriaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CategoriaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgregarCatPro;
    private javax.swing.JButton bttEliminarCatPro;
    private javax.swing.JButton bttSeleccionarCatPro;
    private javax.swing.JButton bttVolverCPC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JList<String> lstCategorias;
    // End of variables declaration//GEN-END:variables
}
