
package Frames;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import Clases.Ciudadano;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class InicioSesionCiu extends javax.swing.JFrame {

    public MolinMy padre;
    private Map<String, Ciudadano> usuariosCiu = new HashMap<>();
    public InicioSesionCiu(MolinMy padre) {
        initComponents();
        this.padre = padre;
    Ciudadano ciu1 = new Ciudadano("Juanito ");
    ciu1.setContraseña("FAS");
    ciu1.setCorreo("aeiou@gmail.com");
    usuariosCiu.put("aeiou@gmail.com", ciu1);
    Ciudadano ciu2 = new Ciudadano("xd");
    ciu2.setContraseña("1");
    ciu2.setCorreo("a");
    usuariosCiu.put("a", ciu2);
    txtCorreoCiu.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        bttInicioSesionCiu.doClick();
    }
});
    pssContraCiu.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        bttInicioSesionCiu.doClick(); 
    }
});
    }

    private InicioSesionCiu() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreoCiu = new javax.swing.JTextField();
        pssContraCiu = new javax.swing.JPasswordField();
        bttInicioSesionCiu = new javax.swing.JButton();
        bttSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Correo");

        jLabel2.setText("Contraseña");

        txtCorreoCiu.setText("jTextField1");
        txtCorreoCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoCiuActionPerformed(evt);
            }
        });

        pssContraCiu.setText("jPasswordField1");
        pssContraCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssContraCiuActionPerformed(evt);
            }
        });

        bttInicioSesionCiu.setText("Iniciar Sesion");
        bttInicioSesionCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttInicioSesionCiuActionPerformed(evt);
            }
        });
        bttInicioSesionCiu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttInicioSesionCiuKeyPressed(evt);
            }
        });

        bttSalir.setText("Salir");
        bttSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCorreoCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(pssContraCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttInicioSesionCiu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bttSalir)
                        .addGap(86, 86, 86))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreoCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pssContraCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttInicioSesionCiu)
                    .addComponent(bttSalir))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttInicioSesionCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioSesionCiuActionPerformed

    String correoIngresado = txtCorreoCiu.getText();
        String contraseñaIngresada = pssContraCiu.getText();

      if (usuariosCiu.containsKey(correoIngresado)) {
    Ciudadano ciu = usuariosCiu.get(correoIngresado);
    if (ciu.getContraseña().equals(contraseñaIngresada)) {
        InicioCiu ventanacurso = new InicioCiu(this,ciu.getNicknameCiu());
        ventanacurso.setVisible(true);
        this.setVisible(false);
        return;
    }
   
}
SwingUtilities.invokeLater(() -> {
    JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Inténtalo de nuevo.");
});
    }//GEN-LAST:event_bttInicioSesionCiuActionPerformed

    private void txtCorreoCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoCiuActionPerformed
   
    }//GEN-LAST:event_txtCorreoCiuActionPerformed

    private void bttSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSalirActionPerformed
        MolinMy ventanacurso = new MolinMy();
        ventanacurso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttSalirActionPerformed

    private void bttInicioSesionCiuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttInicioSesionCiuKeyPressed

    }//GEN-LAST:event_bttInicioSesionCiuKeyPressed

    private void pssContraCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssContraCiuActionPerformed

    }//GEN-LAST:event_pssContraCiuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionCiu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttInicioSesionCiu;
    private javax.swing.JButton bttSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pssContraCiu;
    private javax.swing.JTextField txtCorreoCiu;
    // End of variables declaration//GEN-END:variables
}
