/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

import Clases.ProductoPromocion;
<<<<<<< HEAD
import java.io.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JOptionPane;
=======
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7

/**
 *
 * @author User001
 */
public class ListaProductos extends javax.swing.JFrame {
<<<<<<< HEAD
DefaultListModel<ProductoPromocion> listModel = new DefaultListModel();

    private File selectedFile; 
=======

>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7
    public CategoriaProductos padre;
    public String CategoriaSeleccionada;
    public String nickNameMicro;
    DefaultListModel modele = new DefaultListModel();
    List<ProductoPromocion> promocion = new ArrayList<>();
    public ListaProductos(CategoriaProductos padre,String CategoriaSeleccionada,String nickNameMicro) {
        initComponents();
        this.padre=padre;
        this.CategoriaSeleccionada=CategoriaSeleccionada;
        this.nickNameMicro=nickNameMicro;
        lblRazonSocial.setText(nickNameMicro);
    }

    private ListaProductos() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblRazonSocial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPromociones = new javax.swing.JList<>();
        bttAgregarProducto = new javax.swing.JButton();
        bttEliminarProducto = new javax.swing.JButton();
        bttVolverAPR = new javax.swing.JButton();
<<<<<<< HEAD
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
=======
>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel2.setText("Productos");

        lblRazonSocial.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblRazonSocial.setText("jLabel2");

        lstPromociones.setBackground(new java.awt.Color(179, 255, 179));
        lstPromociones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lstPromociones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lstPromociones);

        bttAgregarProducto.setBackground(new java.awt.Color(230, 255, 230));
        bttAgregarProducto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bttAgregarProducto.setText("Agregar Producto");
        bttAgregarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregarProductoActionPerformed(evt);
            }
        });

        bttEliminarProducto.setBackground(new java.awt.Color(230, 255, 230));
        bttEliminarProducto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bttEliminarProducto.setText("Eliminar Producto");
        bttEliminarProducto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminarProductoActionPerformed(evt);
            }
        });

        bttVolverAPR.setBackground(new java.awt.Color(230, 255, 230));
        bttVolverAPR.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bttVolverAPR.setText("Volver");
        bttVolverAPR.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttVolverAPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttVolverAPRActionPerformed(evt);
            }
        });

<<<<<<< HEAD
        jButton1.setText("Importar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exportar");
        jButton2.setActionCommand("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

=======
>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(141, 141, 141)
                        .addComponent(lblRazonSocial))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(27, 27, 27)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(321, 321, 321)
                            .addComponent(bttEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 30, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
<<<<<<< HEAD
                .addGap(43, 43, 43)
                .addComponent(bttAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(bttVolverAPR, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(20, 20, 20))
=======
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bttAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(bttVolverAPR, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblRazonSocial))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttAgregarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
<<<<<<< HEAD
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttVolverAPR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(15, Short.MAX_VALUE))
=======
                .addComponent(bttVolverAPR, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregarProductoActionPerformed
        AgregarProductos ventanacurso = new AgregarProductos(this);
        ventanacurso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttAgregarProductoActionPerformed

    private void bttEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttEliminarProductoActionPerformed

    private void bttVolverAPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVolverAPRActionPerformed
        padre.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bttVolverAPRActionPerformed

<<<<<<< HEAD
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.showOpenDialog(this);
    selectedFile = fileChooser.getSelectedFile();

    if (selectedFile != null) {
        importarDatos();
    }
}
    
private void importarDatos() {
    try (BufferedReader br = new BufferedReader(new FileReader(selectedFile))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] campos = line.split("\\|");
            if (campos.length == 3) {
                String nombreProducto = campos[0].trim();
                String descripcionProducto = campos[1].trim();
                String precioProducto = campos[2].trim();

                // Crea un nuevo objeto Producto y agrégalo al modelo de la lista
                ProductoPromocion producto = new ProductoPromocion(nombreProducto, descripcionProducto, precioProducto);
                listModel.addElement(producto);
                promocion.add(producto);
                
               
            } else {
                System.err.println("Formato de línea incorrecto: " + line);
            }
        }
        // Actualiza la lista visual con el nuevo modelo
        JList<ProductoPromocion> lstPromociones = new JList<>(listModel);

               lstPromociones.setModel(listModel);
               
               
        JOptionPane.showMessageDialog(this, "Datos importados exitosamente.");
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this, "Error al importar datos: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFileChooser fileChooser = new JFileChooser();
    int result = fileChooser.showSaveDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        // No declares una nueva variable, utiliza la variable de instancia
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(selectedFile))) {
            // Lógica para escribir los datos en el archivo
            for (ProductoPromocion producto : promocion) {
                // Aquí debes convertir cada producto a una cadena de texto
                // y escribirlo en el archivo
                bw.write(producto.toString());
                bw.newLine();
            }
            JOptionPane.showMessageDialog(this, "Datos exportados exitosamente.");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error al exportar datos: " + e.getMessage());
        }
    }
                               
    }//GEN-LAST:event_jButton2ActionPerformed

=======
>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7
     public void agregarProductoALista(String NombreProducto, String DescripcionProducto, String PrecioProducto) {
    ProductoPromocion nuevaPromo = new ProductoPromocion(NombreProducto, DescripcionProducto, PrecioProducto);
    promocion.add(nuevaPromo);
    modele.addElement(NombreProducto + " | " + DescripcionProducto + " | " + PrecioProducto+"soles | "+CategoriaSeleccionada+" | "+ nickNameMicro);
    lstPromociones.setModel(modele);
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttAgregarProducto;
    private javax.swing.JButton bttEliminarProducto;
    private javax.swing.JButton bttVolverAPR;
<<<<<<< HEAD
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
=======
>>>>>>> c6f1e4d840fa97ffa1359c8021c56c9b699f4fc7
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JList<String> lstPromociones;
    // End of variables declaration//GEN-END:variables
}
