
package Frames;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import Clases.Ciudadano;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class InicioSesionCiu extends javax.swing.JFrame {

    public MolinMy padre;
    private Map<String, Ciudadano> usuariosCiu = new HashMap<>();
    public InicioSesionCiu(MolinMy padre) {
        initComponents();
        this.padre = padre;
    Ciudadano ciu1 = new Ciudadano("Juanito ");
    ciu1.setContraseña("FAS");
    ciu1.setCorreo("aeiou@gmail.com");
    usuariosCiu.put("aeiou@gmail.com", ciu1);
    Ciudadano ciu2 = new Ciudadano("xd");
    ciu2.setContraseña("1");
    ciu2.setCorreo("a");
    usuariosCiu.put("a", ciu2);
    txtCorreoCiu.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        bttInicioSesionCiu.doClick();
    }
});
    pssContraCiu.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) {
        bttInicioSesionCiu.doClick(); 
    }
});
    }

    private InicioSesionCiu() {}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCorreoCiu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pssContraCiu = new javax.swing.JPasswordField();
        bttInicioSesionCiu = new javax.swing.JButton();
        bttSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Correo");

        txtCorreoCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoCiuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Contraseña");

        pssContraCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssContraCiuActionPerformed(evt);
            }
        });

        bttInicioSesionCiu.setBackground(new java.awt.Color(230, 255, 230));
        bttInicioSesionCiu.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bttInicioSesionCiu.setText("Iniciar Sesion");
        bttInicioSesionCiu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttInicioSesionCiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttInicioSesionCiuActionPerformed(evt);
            }
        });
        bttInicioSesionCiu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bttInicioSesionCiuKeyPressed(evt);
            }
        });

        bttSalir.setBackground(new java.awt.Color(230, 255, 230));
        bttSalir.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bttSalir.setText("Salir");
        bttSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(bttInicioSesionCiu, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pssContraCiu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(bttSalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreoCiu))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreoCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pssContraCiu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttInicioSesionCiu, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttInicioSesionCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioSesionCiuActionPerformed

    String correoIngresado = txtCorreoCiu.getText();
        String contraseñaIngresada = pssContraCiu.getText();

      if (usuariosCiu.containsKey(correoIngresado)) {
    Ciudadano ciu = usuariosCiu.get(correoIngresado);
    if (ciu.getContraseña().equals(contraseñaIngresada)) {
        InicioCiu ventanacurso = new InicioCiu(this,ciu.getNicknameCiu());
        ventanacurso.setVisible(true);
        this.setVisible(false);
        return;
    }
   
}
SwingUtilities.invokeLater(() -> {
    JOptionPane.showMessageDialog(this, "Credenciales incorrectas. Inténtalo de nuevo.");
});
    }//GEN-LAST:event_bttInicioSesionCiuActionPerformed

    private void txtCorreoCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoCiuActionPerformed
   
    }//GEN-LAST:event_txtCorreoCiuActionPerformed

    private void bttSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSalirActionPerformed
        MolinMy ventanacurso = new MolinMy();
        ventanacurso.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bttSalirActionPerformed

    private void bttInicioSesionCiuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bttInicioSesionCiuKeyPressed

    }//GEN-LAST:event_bttInicioSesionCiuKeyPressed

    private void pssContraCiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssContraCiuActionPerformed

    }//GEN-LAST:event_pssContraCiuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesionCiu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesionCiu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttInicioSesionCiu;
    private javax.swing.JButton bttSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField pssContraCiu;
    private javax.swing.JTextField txtCorreoCiu;
    // End of variables declaration//GEN-END:variables
}
